# Generated by Django 4.2.4 on 2024-11-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.CharField(default="2017", max_length=4),
        ),
    ]
